# taken from
# https://github.com/wincent/wincent/blob/8b725a5311bb4d865589a94b077a14c9ca5c0acd/roles/homebrew/tasks/main.yml
---
- name: homebrew | download Homebrew install script
  get_url:
    url=https://raw.githubusercontent.com/Homebrew/install/master/install
    dest=vendor/homebrew/install

- name: homebrew | install Homebrew
  command: ruby vendor/homebrew/install creates=/usr/local/bin/brew

- name: homebrew | update Homebrew
  homebrew: update_homebrew=yes

- name: homebrew | tap bundle
  homebrew_tap: tap=homebrew/bundle state=present

- name: homebrew | prepare Brewfile
  template: dest="~/Library/Preferences/Brewfile" mode=0644 src=Brewfile

- name: homebrew | bundle
  command: brew bundle chdir="~/Library/Preferences"
